# Generated by Django 5.2.7 on 2025-11-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "color"), ("size", "size")], max_length=100
            ),
        ),
    ]
