# Generated by Django 5.2.7 on 2026-09-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "productgallery",
                "verbose_name_plural": "product gallery",
            },
        ),
    ]
