# Generated by Django 5.2.7 on 2026-09-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_productgallery_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgallery",
            name="image",
            field=models.ImageField(max_length=255, upload_to="photos/store/products"),
        ),
    ]
