# Generated by Django 5.2.7 on 2026-09-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_productgallery_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgallery",
            name="image",
            field=models.ImageField(max_length=255, upload_to="store/products"),
        ),
    ]
