# Generated by Django 5.2.7 on 2026-09-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default/default-user.jpg", upload_to="user-profile"
            ),
        ),
    ]
