# Generated by Django 5.2.7 on 2025-11-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_payment_alter_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="size",
        ),
    ]
